language: node_js
node_js:
- 4.5.0
addons:
  apt:
    packages:
    - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install
deploy:
  provider: releases
  api_key:
    secure: DTnC6X9kMiNXauQTh854OwtqVZpW+iR1ANsjHuI6lSx8vBEYNUERdRoEQi0HsGRlpxVE9aVctTS2DtwcFP0ljVeghIDoPrubCP62YEPq25O4xxt/E3eq+b+DCOkTDaholcOTzfBnOlnW1b7+QjeMv+yM4s9WksELHUjLgQRUlmVqJXpZdx5j2126v4/SllfjOmEV0hVbtkFCwTLcIOl83EiWchVJvbFNJXWN9vnA0UMvyHoxV5urhbr3ktU5V+Jh99zSGKVZzIZPIoLDHdfJ0hzg7TQypUWlEWvKtPkyWnFzqCyix3nXGk3g08joc6L3+5w1FCbEhyJpa4pFPTbK8TR+JlXoiqFNITIxnfUv4CC3yUZTJY+GLhxXVLwfHML6aWPYdFjyEDzBsxoC2sn4LBKcEyzEyoli/wZIZpKXBIoEpGbZB4J9NeNaVJsszqqNYj4LZQH+OHNIx4qx1dp2qnIun7BW4TMgcpDoY9Pkg4g/7NHII6Wujnc2O6t3NV3qG73b/EWqzNGzPtxzWNo4dhVcMfUdG3rzFBS5DBkrPHtWgvkuSEmHS6YyBLsurju74diy4gFxKYTme13NxqD0M1vKbvoHkrN6dCeLh19hUFspba6eIEpa09g1du5toCTLj+KhGEOTiE1AMy8EYn/K1Q9BL+Bm0wbrWrrR0DblpwE=
    secure: QqAz6s5lEYWaRs2SXla8JCVhP4iYFIwg0WnIEqblnecJbdhqkCg7uF6/2qR8b1eVEI1eWdaEpM9PQWF0gjM7Ow/5JQiO86H6wbVACXqyCM1DxJB2GaQSIo5ZamnF/4AbkQSukgQm4NbT2Sw63r+ZIyE4Wokutu3qbBMRGf1zamRlX6a0cDb9/hdeMNt65JIsoe+JQ915VP8TDCti/rm2nZ4Yw5CNInjaS34naamBcf0+IZKvpsrSAHKlB55RosYUO2CZcAdjbrHZsKdf+Q96lvbkZJypCobczxpFjRY7AhtwhzEQsxsSQvvefEnZl1QlWVavDRN4doHSQTk40YSpydLwbY+rlfO4x6dty5Jt5e8qdJ91zvtyU3A7aqLNMceeVMu92C4tNXot7OEF12c/4Qg/5S4eOZ54aaOoj5gmE3oS4QqiiooG+39TRpv13vH1aDrUZeqSLTs2Ww0dPi1qfNoZthlJp3aan34fo4dr/sbNWoo0AMIulR6MORnj7OemdspP3fNlM3Dgr/XauGy9rDTgBznH73swDB3osB58axHCCR6jV4eKAk57ZeQh6QF1Azo01+NSMT9qUOiI9ameHAFDELyvvy+yxLvgCD2Meq6uzxPzsWUdLJfr4PIKXTkhBP29fOFZycijlL+z8/v0u4NhtGP2DvlrT2G0BA0BPuM=
  file: ./build/custom-select.min.js
  skip_cleanup: true
  on:
    repo: custom-select/custom-select
    tags: true
