language: node_js
node_js:
- 4.5.0
addons:
  apt:
    packages:
    - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install
deploy:
  provider: releases
  api_key:
    secure: DTnC6X9kMiNXauQTh854OwtqVZpW+iR1ANsjHuI6lSx8vBEYNUERdRoEQi0HsGRlpxVE9aVctTS2DtwcFP0ljVeghIDoPrubCP62YEPq25O4xxt/E3eq+b+DCOkTDaholcOTzfBnOlnW1b7+QjeMv+yM4s9WksELHUjLgQRUlmVqJXpZdx5j2126v4/SllfjOmEV0hVbtkFCwTLcIOl83EiWchVJvbFNJXWN9vnA0UMvyHoxV5urhbr3ktU5V+Jh99zSGKVZzIZPIoLDHdfJ0hzg7TQypUWlEWvKtPkyWnFzqCyix3nXGk3g08joc6L3+5w1FCbEhyJpa4pFPTbK8TR+JlXoiqFNITIxnfUv4CC3yUZTJY+GLhxXVLwfHML6aWPYdFjyEDzBsxoC2sn4LBKcEyzEyoli/wZIZpKXBIoEpGbZB4J9NeNaVJsszqqNYj4LZQH+OHNIx4qx1dp2qnIun7BW4TMgcpDoY9Pkg4g/7NHII6Wujnc2O6t3NV3qG73b/EWqzNGzPtxzWNo4dhVcMfUdG3rzFBS5DBkrPHtWgvkuSEmHS6YyBLsurju74diy4gFxKYTme13NxqD0M1vKbvoHkrN6dCeLh19hUFspba6eIEpa09g1du5toCTLj+KhGEOTiE1AMy8EYn/K1Q9BL+Bm0wbrWrrR0DblpwE=
    secure: KQbHEi+/4JTQiuiJI1w10lhS0giNyQ6fNd5RNkZ4aOT7kXFexAqRCWvA/naAQ1I4W5Itpheeu+S12jHblY9fa+I4vGQhtYV44fljCg43Jd1Zun1wzhnPRO1zuLABTpDeMFZLr+wf6WH/XbfPpzfBixsg4CGbAYEmoY3sjToTXO4fj6cdHNMr4n5u+EXDl4sCv3CGvSFa7n5cKhX46PJfEn78G0e0l5ler6W7qZgrq7pMSMCV5Ha7pQb01bhkLJSI0AhjiFUAKDYoP/Fm4i53qsiWAS/XhSl2v7VJpe4TcoC75xJVpc234J3v6JQ7va2q7ov0a3wxYWYQWcJ4m/6+Yo6oHXvQSvyZJME38i3mUrE09QsmLgfb4w9pdYxwQ6cQ4Uw5zx/SRIcQIBOGTDe3t+oZSUPzTvXhAkk3Jnp3+ELMvOGqDmhfe/CUpc79BX0ajbYkG7tQ3UwyOZ/mAwYYPNOliSXn8yiR5+chH115b9mrtT44syBmgWNQRX32+f3uwHMfY+wBN9rlv1mAZFn2hkjvTSEVHZ4yr18NfTWmogrqVPdrsnniSOwbBdFDHUuHKdEklDjcS3j/Qo5GhMGAxUwz9Dt1m9v5XXNATtt0P/slhEGSCpGKpZfZAJwLiFe0YwbT5hymSXQBAoc7LeccE3QECACj/JlJXFEspBmJXFg=
  file:
    - "./build/custom-select.min.js"
    - "./build/jquery.custom-select.min.js"
    - "./build/custom-select.css"
  skip_cleanup: true
  on:
    repo: custom-select/custom-select
    tags: true
